<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.5</version>
		<relativePath/>
	</parent>

	<groupId>com.ns</groupId>
	<artifactId>toodles</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>toodles-parent</name>
	<description>Parent project for modular tools</description>

	<packaging>pom</packaging>

	<properties>
		<java.version>17</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<axis2.version>1.7.9</axis2.version>
	</properties>

	<modules>
		<module>wsdl-module</module>
		<module>launcher-module</module>
		<module>importResolver-module</module>
        <module>common-module</module>
    </modules>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.ns</groupId>
				<artifactId>common-module</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.ns</groupId>
				<artifactId>wsdl-module</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.ns</groupId>
				<artifactId>import-module</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.ns</groupId>
				<artifactId>status-module</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

</project>